import Foundation

// MARK: - Entorno de shell (P-09 consentimiento · P-13 política única)

/// Generación y política del fichero de entorno que conecta los agentes de terminal
/// con el puerto activo, más la inyección del `source` en `~/.zshrc`.
public enum ShellEnvironment {
    public static let fileName = ".splash_monitor_env"
    /// Encabezado que identifica la inyección en `~/.zshrc`. Es a la vez la marca de
    /// detección y el ancla de la reversión, así que generación y borrado no pueden
    /// desincronizarse.
    public static let blockHeader = "# Splash Monitor — port environment"

    /// Contenido completo del fichero de entorno.
    public static func fileContents(port: Int) -> String {
        """
        # Splash Monitor — auto-generated environment (do not edit manually)
        # Generated by Splash Monitor for port \(port)
        export SPLASH_PORT="\(port)"
        export ANTHROPIC_BASE_URL="http://127.0.0.1:\(port)"
        export OPENAI_BASE_URL="http://127.0.0.1:\(port)/v1"
        """
    }

    public static func sourceLine(envFilePath: String) -> String {
        "[ -f \"\(envFilePath)\" ] && source \"\(envFilePath)\""
    }

    public static func injectionBlock(envFilePath: String) -> String {
        "\n\n\(blockHeader)\n\(sourceLine(envFilePath: envFilePath))\n"
    }

    public static func needsInjection(into zshrcContents: String) -> Bool {
        !zshrcContents.contains(blockHeader)
    }

    /// Reversión exacta de la inyección tal y como la escribe la app: elimina el
    /// separador añadido, el comentario y la línea `source`.
    /// La app escribía en `~/.zshrc` sin ofrecer forma de deshacerlo (P-09).
    public static func removingInjection(from zshrcContents: String) -> String {
        guard let range = zshrcContents.range(of: blockHeader) else { return zshrcContents }
        var head = String(zshrcContents[zshrcContents.startIndex..<range.lowerBound])
        var remainder = String(zshrcContents[range.upperBound...])
        
        // Separador que precede al bloque (los dos saltos que añade `injectionBlock`).
        var separatorsToDrop = 2
        while separatorsToDrop > 0, head.hasSuffix("\n") {
            head.removeLast()
            separatorsToDrop -= 1
        }
        // Resto de la línea del comentario y la línea del `source`.
        var linesToDrop = 2
        while linesToDrop > 0, let newline = remainder.firstIndex(of: "\n") {
            remainder = String(remainder[remainder.index(after: newline)...])
            linesToDrop -= 1
        }
        return head + remainder
    }

    /// Política única de sincronización (P-13).
    ///
    /// Antes: `startServer()` borraba el fichero si el puerto era 8000 mientras
    /// `checkServerStatus()` lo escribía también para 8000. Dos reglas opuestas para
    /// el mismo caso. Regla única: el entorno se sincroniza **siempre**, porque los
    /// agentes necesitan las variables aunque el puerto sea el predeterminado.
    public static func shouldSync(port: Int) -> Bool {
        port > 0 && port <= 65535
    }
}

/// Consentimiento para escribir fuera del directorio de datos de la app (P-09 / H-09).
public enum ShellConsent {
    public enum Decision: Equatable {
        case write            // ya autorizado
        case askUser          // requiere diálogo explicativo
        case skip             // denegado: no se toca nada
    }

    public static func decide(hasConsent: Bool, userDeclined: Bool) -> Decision {
        if hasConsent { return .write }
        if userDeclined { return .skip }
        return .askUser
    }
}
